language: python
python:
  - "2.7"
install:
  - pushd $HOME
  - curl -L -O https://cdn.alliedvision.com/fileadmin/content/software/software/Vimba/Vimba_v2.0_Linux.tgz
  - tar -xf Vimba_v2.0_Linux.tgz
  - export VIMBA_ROOT="$PWD/Vimba_2_0"
  - popd
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy matplotlib nose cython numexpr pyzmq pyserial
  - source activate test-environment
  - conda install pandas
  #- conda install opencv
  - pip install opencv-python
  #- pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
  - pip install blosc
  - pip install Pyro4
  - pip install cobs
  - pip install ipython
  - pip install PyCRC
  - pip install pillow
  # --
  - pushd $HOME
  - git clone --depth=10 --branch=master https://github.com/labjack/LabJackPython.git
  - cd LabJackPython
  - pip install .
  - popd
  - nosetests --plugins
after_success:
  - codecov

script: 
  - pushd pmc_camera/pycamera/_pyvimba
  - make
  - popd
  - "nosetests -v -s --with-coverage --cover-erase --cover-xml --cover-inclusive --cover-package=pmc_camera
    --cover-package=housekeeping"
