language: python
python:
  - "2.7"
install:
  - curl -L -O https://cdn.alliedvision.com/fileadmin/content/software/software/Vimba/Vimba_v2.0_Linux.tgz
  - tar -xf Vimba_v2.0_Linux.tgz
  - export VIMBA_ROOT="$PWD/Vimba_2_0"
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy matplotlib nose cython numexpr pyzmq pyserial netCDF4
  - source activate test-environment
  - conda install -c blosc python-blosc
  - conda install opencv
  #- pip install -r requirements.txt
  - pip install codecov
after_success:
  - codecov

script: 
  - cd pmc_camera/pycamera/_pyvimba
  - make
  - cd ../../..
  - nosetests -v --with-coverage --cover-erase --cover-xml --cover-inclusive --cover-package=pmc_camera
