channels:
- 'conda-forge'
- 'defaults'
dependencies:
- 'astropy=1.3=np111py27_0'
- 'backports=1.0=py27_0'
- 'cairo=1.14.8=0'
- 'cycler=0.10.0=py27_0'
- 'cython=0.25.2=py27_0'
- 'dbus=1.10.10=0'
- 'decorator=4.0.11=py27_0'
- 'enum34=1.1.6=py27_0'
- 'expat=2.1.0=0'
- 'fontconfig=2.12.1=3'
- 'freetype=2.5.5=2'
- 'functools32=3.2.3.2=py27_0'
- 'get_terminal_size=1.0.0=py27_0'
- 'glib=2.50.2=1'
- 'gst-plugins-base=1.8.0=0'
- 'gstreamer=1.8.0=0'
- 'harfbuzz=0.9.39=2'
- 'hdf5=1.8.17=1'
- 'icu=54.1=0'
- 'ipython=5.2.2=py27_0'
- 'ipython_genutils=0.1.0=py27_0'
- 'jbig=2.1=0'
- 'jpeg=9b=0'
- 'libffi=3.2.1=1'
- 'libgcc=5.2.0=0'
- 'libgfortran=3.0.0=1'
- 'libiconv=1.14=0'
- 'libpng=1.6.27=0'
- 'libtiff=4.0.6=3'
- 'libxcb=1.12=1'
- 'libxml2=2.9.4=0'
- 'matplotlib=2.0.0=np111py27_0'
- 'mkl=2017.0.1=0'
- 'nose=1.3.7=py27_1'
- 'numexpr=2.6.2=np111py27_0'
- 'numpy=1.11.3=py27_0'
- 'openssl=1.0.2k=0'
- 'pandas=0.19.2=np111py27_1'
- 'path.py=10.1=py27_0'
- 'pathlib2=2.2.0=py27_0'
- 'pcre=8.39=1'
- 'pexpect=4.2.1=py27_0'
- 'pickleshare=0.7.4=py27_0'
- 'pip=9.0.1=py27_1'
- 'pixman=0.34.0=0'
- 'prompt_toolkit=1.0.9=py27_0'
- 'ptyprocess=0.5.1=py27_0'
- 'pycairo=1.10.0=py27_0'
- 'pygments=2.1.3=py27_0'
- 'pyparsing=2.1.4=py27_0'
- 'pyqt=5.6.0=py27_2'
- 'pyserial=2.7=py27_0'
- 'python=2.7.13=0'
- 'python-dateutil=2.6.0=py27_0'
- 'pytz=2016.10=py27_0'
- 'pyyaml=3.12=py27_0'
- 'qt=5.6.2=3'
- 'readline=6.2=2'
- 'scandir=1.4=py27_0'
- 'scipy=0.18.1=np111py27_1'
- 'setuptools=27.2.0=py27_0'
- 'simplegeneric=0.8.1=py27_1'
- 'sip=4.18=py27_0'
- 'six=1.10.0=py27_0'
- 'sqlite=3.13.0=0'
- 'subprocess32=3.2.7=py27_0'
- 'tk=8.5.18=0'
- 'traitlets=4.3.1=py27_0'
- 'wcwidth=0.1.7=py27_0'
- 'wheel=0.29.0=py27_0'
- 'xz=5.2.2=1'
- 'yaml=0.1.6=0'
- 'zlib=1.2.8=3'
- 'opencv' #=3.2.0'
- pip:
  - attrs==16.3.0
  - automat==0.5.0
  - backports.shutil-get-terminal-size==1.0.0
  - blosc==1.5.0
  - cobs==1.0.0
  - coloredlogs==5.2
  - constantly==15.1.0
  - humanfriendly==2.4
  - incremental==16.10.1
  - ipython-genutils==0.1.0
  - monotonic==1.2
  - olefile==0.44
  - orderedattrdict==1.4.3
  - pillow==4.0.0
  - prompt-toolkit==1.0.9
  - pycrc==1.21
  - pymodbus==1.2.0
  - pynmea2==1.7.1
  - pyro4==4.55
  - selectors34==1.1
  - serpent==1.18
  - twisted==17.1.0
  - zope.interface==4.3.3


