dependencies:
- astropy=1.2.1=np111py27_0
- backports=1.0=py27_0
- cairo=1.12.18=6
- curl=7.49.0=1
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- joblib=0.9.4=py27_0
- jpeg=8d=1
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libnetcdf=4.4.1=0
- libpng=1.6.17=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.3=0
- netcdf4=1.2.4=np111py27_0
- nose=1.3.7=py27_1
- numexpr=2.6.1=np111py27_0
- numpy=1.11.2=py27_0
- opencv=2.4.10=np110py27_1
- openssl=1.0.2j=0
- pandas=0.19.1=np111py27_0
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=9.0.1=py27_1
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- psutil=4.4.2=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- pyserial=2.7=py27_0
- python=2.7.12=1
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- pyzmq=15.4.0=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.18.0=np111py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - blosc==1.5.0
  - cobs==1.0.0
  - coloredlogs==5.2
  - constantly==15.1.0
  - coverage==4.2
  - humanfriendly==2.3.2
  - incremental==16.10.1
  - ipython-genutils==0.1.0
#  - labjackpython (/home/pmc/pmchome/LabJackPython/src)==5 26 2015
  - mdstat==1.0.4
  - monotonic==1.2
  - orderedattrdict==1.4.3
  - pillow==3.4.2
  - prompt-toolkit==1.0.3
  - pycrc==1.21
  - pymodbus==1.2.0
  - pyro4==4.53
  - pyyaml==3.12
  - selectors34==1.1
  - serpent==1.16
  - twisted==16.5.0
  - zope.interface==4.3.2

